const theme = {
  borderRadius: {
    boxes: '8px',
    buttons: '6px',
    inputs: '6px',
  },

  colors: {
    green_100: '#e8f6f3',
    green_200: '#d2ede7',
    green_500: '#00A385',
    primary_50: '#FFC62C',
    primary_100: '#F8B500',
    primary_200: '#C59000',
    primary_300: '#8DB1FF',
    primary_400: '#419EF4',
    primary_500: '#1173E7',
    primary_700: '#0F5EBC',
    primary_800: '#030D6E',
    primary_900: '#02374a',
    accent_purple: '#C292FF',
    accent_orange: '#FFA64E',
    accent_green: '#00A385',
    accent_green_light: '#66CD95',
    accent_blue: '#419EF4',
    accent_red: '#FF5454',
    accent_yellow: '#FFCD4E',
    neutral_25: '#F7F7F7',
    neutral_50: '#505762',
    neutral_200: '#393E46',
    neutral_400: '#B5BABD',
    neutral_600: '#6D7275',
    neutral_800: '#3D4042',
    neutral_900: '#1E2021',
    neutral_white: '#FFFFFF',
    neutral_black: '#000000',
    error_25: '#FFECEF',
    error_200: '#F09D9E',
    error_400: '#D63737',
    bgMain: '#F8F9FA',
    bgBlue: '#042940',
    linkColor: '#3648f8',
  },

  fontScale: {
    superHero: {
      size: '65px',
      lineHeight: '65px',
      letterSpacing: '0px',
    },
    hero: {
      size: '36px',
      lineHeight: '40px',
      letterSpacing: '0px',
    },
    extraLarge: {
      size: '32px',
      lineHeight: '36px',
      letterSpacing: '0px',
    },
    superLarge: {
      size: '28px',
      lineHeight: '32px',
      letterSpacing: '0px',
    },
    large: {
      size: '24px',
      lineHeight: '30px',
      letterSpacing: '0px',
    },
    big: {
      size: '18px',
      lineHeight: '24px',
      letterSpacing: '0px',
    },
    medium: {
      size: '16px',
      lineHeight: '22px',
      letterSpacing: '0.25px',
    },
    small: {
      size: '14px',
      lineHeight: '18px',
      letterSpacing: '0.25px',
    },
    extraSmall: {
      size: '12px',
      lineHeight: '16px',
      letterSpacing: '0.25px',
    },
  },
  font: {
    family: {
      main: "'Outfit', sans-serif",
      secondary: "'PT Sans', sans-serif",
    },
  },

  breakpoints: {
    mobileS: `(min-width: 320px)`,
    mobileM: `(min-width: 375px)`,
    mobileL: `(min-width: 475px)`,
    mobileXL: `(min-width: 576px)`,
    tablet: `(min-width: 768px)`,
    laptop: `(min-width: 1024px)`,
    laptopM: `(min-width: 1280px)`,
    laptopL: `(min-width: 1366px)`,
    desktop: `(min-width: 1700px)`,
    desktopXL: `(min-width: 2500px)`,
  },

  layoutPadding: {
    mobile: '5%',
    tablet: '5%',
    full: '0px',
    main: '10%',
    ultra: '33%',
  },

  spacing: {
    _01: '4px',
    _02: '8px',
    _03: '12px',
    _04: '16px',
    _05: '24px',
    _06: '32px',
    _07: '48px',
    _08: '56px',
    _09: '64px',
    _10: '96px',
    _11: '128px',
  },

  transition: {
    duration: '.4s',
    timingFunction: 'ease',
  },

  ctas: {
    primary: {
      background: 'linear-gradient(0deg, #C59000 0%, #FFC62C 100%)',
      borderColor: 'transparent',
      border: '0px',
      hover: {
        background: 'linear-gradient(0deg, #C59000 0%, #FFF62C 100%)',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#C59000',
      },
      disabled: {
        background: '#DBE1E5',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#B5BABD',
      },
      padding: '12px 32px',
      textColor: '#1E2021',
    },
    secondary: {
      background: 'linear-gradient(0deg, #808782 0%, #C7C7C7 100%)',
      borderColor: '#00A385',
      border: '0px',
      hover: {
        background: '#00A3851A',
        borderColor: '#00A385',
        border: '0px',
        textColor: '#FFFFFF',
      },
      disabled: {
        background: '#DBE1E5',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#B5BABD',
      },
      padding: null,
      textColor: '#F7F7F7',
    },
    tertiary: {
      background: 'linear-gradient(0deg, #032520 0%, #042940 100%)',
      borderColor: 'transparent',
      border: '0px',
      hover: {
        background: '#00A3851A',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#00A385',
      },
      disabled: {
        background: 'transparent',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#B5BABD',
      },
      padding: null,
      textColor: '#F7F7F7',
    },
    red: {
      background: 'transparent',
      borderColor: '#D63737',
      border: '2px',
      hover: {
        background: '#F09D9E',
        borderColor: '#D63737',
        border: '2px',
        textColor: '#D63737',
      },
      disabled: {
        background: '#DBE1E5',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#B5BABD',
      },
      padding: null,
      textColor: '#D63737',
    },
    gray: {
      background: 'transparent',
      borderColor: '#6D7275',
      border: '2px',
      hover: {
        background: '#DBE1E5',
        borderColor: '#6D7275',
        border: '2px',
        textColor: '#6D7275',
      },
      disabled: {
        background: '#DBE1E5',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#B5BABD',
      },
      padding: null,
      textColor: '#6D7275',
    },
    disclaimer: {
      background: 'transparent',
      borderColor: '#1E2021',
      border: '1px',
      hover: {
        background: '#1E2021',
        borderColor: '#1E2021',
        border: '1px',
        textColor: '#FFFFFF',
      },
      padding: '6px 30px',
      textColor: '#1E2021',
    },
    state: {
      background: '#FFCD4E',
      borderColor: 'transparent',
      border: '0px',
      disabled: {
        background: '#DBE1E5',
        borderColor: 'transparent',
        border: '0px',
        textColor: '#B5BABD',
      },
      padding: '2px 24px',
      textColor: '#1E2021',
    },
  },
};

export default theme;
